name: Tauri Windows build

on:
  workflow_dispatch: {}
  push:
    tags: ["v*.*.*"]   # run when you push a tag like v0.1.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install NSIS (for .exe installer)
        run: choco install nsis -y

      - name: Install deps
        run: npm ci

      - name: Build Tauri (NSIS)
        run: npm run tauri build -- --bundles nsis

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/tauri_labels.exe
