name: tauri-release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix: { os: [macos-latest, windows-latest, ubuntu-latest] }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - run: npm ci
      - run: npx tauri build   # requires @tauri-apps/cli in devDependencies

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: src-tauri/target/release/bundle/**/*

