name: Tauri Windows build

on:
  workflow_dispatch: {}
  push:
    tags: ["v*.*.*"]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install NSIS (for .exe installer)
        run: choco install nsis -y

      - name: Install deps
        run: npm ci

      - name: Build Tauri (NSIS)
        run: npm run tauri build -- --bundles nsis

      # NEW: show what got produced so we can confirm paths in the logs
      - name: List build outputs
        shell: pwsh
        run: |
          Write-Host "=== TREE: src-tauri\\target ==="
          Get-ChildItem -Path src-tauri\target -Recurse -File | Select-Object FullName

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: |
            src-tauri/target/**/bundle/nsis/*.exe
            src-tauri/target/**/release/*.exe
